// <auto-generated />
using System;
using AppTemplate.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppTemplate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250829192144_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppTemplate.Domain.AppUsers.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("biography");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UserChangedItsUsername")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("user_changed_its_username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 521, DateTimeKind.Utc).AddTicks(2845),
                            IdentityId = "b3398ff2-1b43-4af7-812d-eb4347eecbb8",
                            UserChangedItsUsername = false
                        });
                });

            modelBuilder.Entity("AppTemplate.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When the notification was created");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the notification has been read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Notification message");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasComment("The ID of the user who owns this notification");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Notification title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Notification type");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("IX_Notifications_CreatedOnUtc")
                        .HasFilter("\"DeletedOnUtc\" IS NULL");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("IX_Notifications_RecipientId")
                        .HasFilter("\"DeletedOnUtc\" IS NULL");

                    b.HasIndex("RecipientId", "IsRead")
                        .HasDatabaseName("IX_Notifications_RecipientId_IsRead")
                        .HasFilter("\"DeletedOnUtc\" IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RecipientId", "IsRead"), new[] { "CreatedOnUtc", "Title" });

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("AppTemplate.Domain.Roles.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8a25b63-74ee-4375-98c8-e64107bb6d76"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 528, DateTimeKind.Utc).AddTicks(9977),
                            Feature = "users",
                            Name = "users:admin"
                        },
                        new
                        {
                            Id = new Guid("33261a4a-c423-4876-8f15-e40068aea5ca"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1322),
                            Feature = "users",
                            Name = "users:read"
                        },
                        new
                        {
                            Id = new Guid("9f79a54c-0b54-4de5-94b9-8582a5f32e78"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1328),
                            Feature = "users",
                            Name = "users:create"
                        },
                        new
                        {
                            Id = new Guid("25bb194c-ea15-4339-9f45-5a895c51b626"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1329),
                            Feature = "users",
                            Name = "users:update"
                        },
                        new
                        {
                            Id = new Guid("559dd4ec-4d2e-479d-a0a9-5229ecc04fb4"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1330),
                            Feature = "users",
                            Name = "users:delete"
                        },
                        new
                        {
                            Id = new Guid("6203c108-2c3d-4ed3-ab3c-b119e7a7491a"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1334),
                            Feature = "roles",
                            Name = "roles:admin"
                        },
                        new
                        {
                            Id = new Guid("d066e4ee-6af2-4857-bd40-b9b058fa2201"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1335),
                            Feature = "roles",
                            Name = "roles:read"
                        },
                        new
                        {
                            Id = new Guid("940c88ad-24fe-4d86-a982-fa5ea224edba"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1336),
                            Feature = "roles",
                            Name = "roles:create"
                        },
                        new
                        {
                            Id = new Guid("346d3cc6-ac81-42b1-8539-cd53f42b6566"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1338),
                            Feature = "roles",
                            Name = "roles:update"
                        },
                        new
                        {
                            Id = new Guid("386e40e9-da38-4d2f-8d02-ac4cbaddf760"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1339),
                            Feature = "roles",
                            Name = "roles:delete"
                        },
                        new
                        {
                            Id = new Guid("0eeb5f27-10fd-430a-9257-a8457107141a"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1341),
                            Feature = "permissions",
                            Name = "permissions:read"
                        },
                        new
                        {
                            Id = new Guid("3050d953-5dcf-4eb0-a18d-a3ce62a0dd3c"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1342),
                            Feature = "auditlogs",
                            Name = "auditlogs:read"
                        },
                        new
                        {
                            Id = new Guid("a03a127b-9a03-46a0-b709-b6919f2598be"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1343),
                            Feature = "notifications",
                            Name = "notifications:read"
                        },
                        new
                        {
                            Id = new Guid("a5585e9e-ec65-431b-9bb9-9bbc1663ebb8"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1345),
                            Feature = "notifications",
                            Name = "notifications:update"
                        },
                        new
                        {
                            Id = new Guid("8f97aeb9-a9fd-470f-bae9-c9f5f0534d23"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1346),
                            Feature = "statistics",
                            Name = "statistics:read"
                        },
                        new
                        {
                            Id = new Guid("ee1be42d-4341-4ac5-9390-2ec71eb54239"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1348),
                            Feature = "userfollows",
                            Name = "userfollows:read"
                        },
                        new
                        {
                            Id = new Guid("78f1b087-3b45-48d0-8e16-9f04a760c294"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1349),
                            Feature = "userfollows",
                            Name = "userfollows:create"
                        },
                        new
                        {
                            Id = new Guid("22c1dbc9-bad6-4ebf-9c49-5577625f2b5f"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1350),
                            Feature = "userfollows",
                            Name = "userfollows:update"
                        },
                        new
                        {
                            Id = new Guid("7b834e3d-ff31-416f-8b1e-ce1a7e9681e8"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1352),
                            Feature = "userfollows",
                            Name = "userfollows:delete"
                        },
                        new
                        {
                            Id = new Guid("f14a636e-6a91-4b3e-9ea4-d9bbe8c36872"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1353),
                            Feature = "entries",
                            Name = "entries:admin"
                        },
                        new
                        {
                            Id = new Guid("cd552577-20c8-4e12-9685-a5c24ecd7fa8"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1354),
                            Feature = "entries",
                            Name = "entries:read"
                        },
                        new
                        {
                            Id = new Guid("8116c67b-7f82-41b5-b9c4-a91e042e9257"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1356),
                            Feature = "entries",
                            Name = "entries:create"
                        },
                        new
                        {
                            Id = new Guid("b11364e1-dc05-422f-982a-6f365c1825a8"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1357),
                            Feature = "entries",
                            Name = "entries:update"
                        },
                        new
                        {
                            Id = new Guid("638a9f7e-7bfe-4748-8947-f605c799d214"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1358),
                            Feature = "entries",
                            Name = "entries:delete"
                        },
                        new
                        {
                            Id = new Guid("9185d676-db9e-4a8e-8286-7f4ea78ab022"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1437),
                            Feature = "titles",
                            Name = "titles:admin"
                        },
                        new
                        {
                            Id = new Guid("6030de9b-595c-474f-99ff-b654ad062e19"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1438),
                            Feature = "titles",
                            Name = "titles:read"
                        },
                        new
                        {
                            Id = new Guid("272c16b9-da69-4065-b849-6fb45c9ff281"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1440),
                            Feature = "titles",
                            Name = "titles:create"
                        },
                        new
                        {
                            Id = new Guid("e033b219-f1c5-4c0c-b1f4-a756facb1819"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1441),
                            Feature = "titles",
                            Name = "titles:update"
                        },
                        new
                        {
                            Id = new Guid("48c15b07-004d-44eb-a348-8ae63327a4b8"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1442),
                            Feature = "titles",
                            Name = "titles:delete"
                        },
                        new
                        {
                            Id = new Guid("ec733d3f-cf8b-475c-8af6-5881cdb65dbe"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1444),
                            Feature = "titlefollows",
                            Name = "titlefollows:read"
                        },
                        new
                        {
                            Id = new Guid("1ff035a6-5d40-4a2d-aa9c-1d3182b3642e"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1445),
                            Feature = "titlefollows",
                            Name = "titlefollows:create"
                        },
                        new
                        {
                            Id = new Guid("ac804e8f-abe7-4516-927f-045477dbe007"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1446),
                            Feature = "titlefollows",
                            Name = "titlefollows:update"
                        },
                        new
                        {
                            Id = new Guid("5341ddd6-5c42-477a-a155-33c51030f76b"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1448),
                            Feature = "titlefollows",
                            Name = "titlefollows:delete"
                        },
                        new
                        {
                            Id = new Guid("fbeb18d0-5e5f-4a38-aec7-6bb314408dc7"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1449),
                            Feature = "entrylikes",
                            Name = "entrylikes:read"
                        },
                        new
                        {
                            Id = new Guid("5be9a36e-c59c-4a9a-a800-15f4f76ea80b"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1451),
                            Feature = "entrylikes",
                            Name = "entrylikes:create"
                        },
                        new
                        {
                            Id = new Guid("b2fe4d1c-59b9-4161-8eab-04380b45fd5e"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1452),
                            Feature = "entrylikes",
                            Name = "entrylikes:update"
                        },
                        new
                        {
                            Id = new Guid("bb5cb9b7-75d0-4a9f-81d9-d02259b6ddf2"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1453),
                            Feature = "entrylikes",
                            Name = "entrylikes:delete"
                        },
                        new
                        {
                            Id = new Guid("5bc63b8d-2825-4f0e-aeae-234c7b2d930f"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1455),
                            Feature = "entrybookmarks",
                            Name = "entrybookmarks:read"
                        },
                        new
                        {
                            Id = new Guid("30bb7d98-1a11-4152-9481-9a9d5fd39041"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1456),
                            Feature = "entrybookmarks",
                            Name = "entrybookmarks:create"
                        },
                        new
                        {
                            Id = new Guid("afe7776a-69a6-4134-96ea-a24829c67c9d"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1457),
                            Feature = "entrybookmarks",
                            Name = "entrybookmarks:update"
                        },
                        new
                        {
                            Id = new Guid("8694cd0d-8987-44b4-b823-3f2e7f023919"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1459),
                            Feature = "entrybookmarks",
                            Name = "entrybookmarks:delete"
                        },
                        new
                        {
                            Id = new Guid("859de6a2-9975-4d49-99fb-0a99cb8b3474"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1460),
                            Feature = "entryreports",
                            Name = "entryreports:admin"
                        },
                        new
                        {
                            Id = new Guid("e5f82d92-0610-4f63-ba1c-9bad3cbc09dd"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1461),
                            Feature = "entryreports",
                            Name = "entryreports:read"
                        },
                        new
                        {
                            Id = new Guid("c42c3f31-f94a-474d-a159-2c826c031e34"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1463),
                            Feature = "entryreports",
                            Name = "entryreports:create"
                        },
                        new
                        {
                            Id = new Guid("a393e161-dc5e-4f0c-9fb9-f3a901b48149"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1464),
                            Feature = "entryreports",
                            Name = "entryreports:update"
                        },
                        new
                        {
                            Id = new Guid("33ffe115-42c7-457a-8c63-1f8c5179bb5c"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1465),
                            Feature = "entryreports",
                            Name = "entryreports:delete"
                        },
                        new
                        {
                            Id = new Guid("828736bc-1b6a-4b24-a55a-763fb6616970"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1467),
                            Feature = "featuredentries",
                            Name = "featuredentries:admin"
                        },
                        new
                        {
                            Id = new Guid("fa8626a7-e34f-48c3-8b14-64b6889a36fc"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1468),
                            Feature = "featuredentries",
                            Name = "featuredentries:read"
                        },
                        new
                        {
                            Id = new Guid("5ca7e876-17bb-4b7a-a1d5-42ed0ee6baf3"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1469),
                            Feature = "featuredentries",
                            Name = "featuredentries:create"
                        },
                        new
                        {
                            Id = new Guid("70a3a380-6e15-4b0e-b8b5-67591dbafcfa"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1471),
                            Feature = "featuredentries",
                            Name = "featuredentries:update"
                        },
                        new
                        {
                            Id = new Guid("481770d7-09f7-481a-83cd-f6aa808a072e"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 529, DateTimeKind.Utc).AddTicks(1472),
                            Feature = "featuredentries",
                            Name = "featuredentries:delete"
                        });
                });

            modelBuilder.Entity("AppTemplate.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 534, DateTimeKind.Utc).AddTicks(3770),
                            DisplayName = "yönetici",
                            IsDefault = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            CreatedOnUtc = new DateTime(2025, 8, 29, 19, 21, 43, 534, DateTimeKind.Utc).AddTicks(4460),
                            DisplayName = "kayıtlı",
                            IsDefault = true,
                            Name = "Registered"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b3398ff2-1b43-4af7-812d-eb4347eecbb8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a7b2b66-a436-4c57-acda-4a07b33a86e1",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOi1e+VkZQHzYs4FmanIZGjgxSFTGNWNa4/sDWIg0w5+XBiTC0ckNEZZqnvj3DhiDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "adc0d89d-fa2e-43fd-8bcd-bc109e2508ec",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Myrtus.Clarity.Core.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("33261a4a-c423-4876-8f15-e40068aea5ca")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("9f79a54c-0b54-4de5-94b9-8582a5f32e78")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("25bb194c-ea15-4339-9f45-5a895c51b626")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("559dd4ec-4d2e-479d-a0a9-5229ecc04fb4")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("d066e4ee-6af2-4857-bd40-b9b058fa2201")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("940c88ad-24fe-4d86-a982-fa5ea224edba")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("346d3cc6-ac81-42b1-8539-cd53f42b6566")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("386e40e9-da38-4d2f-8d02-ac4cbaddf760")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("0eeb5f27-10fd-430a-9257-a8457107141a")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("3050d953-5dcf-4eb0-a18d-a3ce62a0dd3c")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("a03a127b-9a03-46a0-b709-b6919f2598be")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("a5585e9e-ec65-431b-9bb9-9bbc1663ebb8")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("c8a25b63-74ee-4375-98c8-e64107bb6d76")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("6203c108-2c3d-4ed3-ab3c-b119e7a7491a")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("8f97aeb9-a9fd-470f-bae9-c9f5f0534d23")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("ee1be42d-4341-4ac5-9390-2ec71eb54239")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("78f1b087-3b45-48d0-8e16-9f04a760c294")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("22c1dbc9-bad6-4ebf-9c49-5577625f2b5f")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("7b834e3d-ff31-416f-8b1e-ce1a7e9681e8")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("f14a636e-6a91-4b3e-9ea4-d9bbe8c36872")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("cd552577-20c8-4e12-9685-a5c24ecd7fa8")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("8116c67b-7f82-41b5-b9c4-a91e042e9257")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("b11364e1-dc05-422f-982a-6f365c1825a8")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("638a9f7e-7bfe-4748-8947-f605c799d214")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("9185d676-db9e-4a8e-8286-7f4ea78ab022")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("6030de9b-595c-474f-99ff-b654ad062e19")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("272c16b9-da69-4065-b849-6fb45c9ff281")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("e033b219-f1c5-4c0c-b1f4-a756facb1819")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("48c15b07-004d-44eb-a348-8ae63327a4b8")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("ec733d3f-cf8b-475c-8af6-5881cdb65dbe")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("1ff035a6-5d40-4a2d-aa9c-1d3182b3642e")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("ac804e8f-abe7-4516-927f-045477dbe007")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("5341ddd6-5c42-477a-a155-33c51030f76b")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("fbeb18d0-5e5f-4a38-aec7-6bb314408dc7")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("5be9a36e-c59c-4a9a-a800-15f4f76ea80b")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("b2fe4d1c-59b9-4161-8eab-04380b45fd5e")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("bb5cb9b7-75d0-4a9f-81d9-d02259b6ddf2")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("5bc63b8d-2825-4f0e-aeae-234c7b2d930f")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("30bb7d98-1a11-4152-9481-9a9d5fd39041")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("afe7776a-69a6-4134-96ea-a24829c67c9d")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("8694cd0d-8987-44b4-b823-3f2e7f023919")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("859de6a2-9975-4d49-99fb-0a99cb8b3474")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("e5f82d92-0610-4f63-ba1c-9bad3cbc09dd")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("c42c3f31-f94a-474d-a159-2c826c031e34")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("a393e161-dc5e-4f0c-9fb9-f3a901b48149")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("33ffe115-42c7-457a-8c63-1f8c5179bb5c")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("828736bc-1b6a-4b24-a55a-763fb6616970")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("fa8626a7-e34f-48c3-8b14-64b6889a36fc")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("5ca7e876-17bb-4b7a-a1d5-42ed0ee6baf3")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("70a3a380-6e15-4b0e-b8b5-67591dbafcfa")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("481770d7-09f7-481a-83cd-f6aa808a072e")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("a03a127b-9a03-46a0-b709-b6919f2598be")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("a5585e9e-ec65-431b-9bb9-9bbc1663ebb8")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("33261a4a-c423-4876-8f15-e40068aea5ca")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("8116c67b-7f82-41b5-b9c4-a91e042e9257")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("cd552577-20c8-4e12-9685-a5c24ecd7fa8")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("b11364e1-dc05-422f-982a-6f365c1825a8")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("638a9f7e-7bfe-4748-8947-f605c799d214")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("272c16b9-da69-4065-b849-6fb45c9ff281")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("6030de9b-595c-474f-99ff-b654ad062e19")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("e033b219-f1c5-4c0c-b1f4-a756facb1819")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("78f1b087-3b45-48d0-8e16-9f04a760c294")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("ee1be42d-4341-4ac5-9390-2ec71eb54239")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("22c1dbc9-bad6-4ebf-9c49-5577625f2b5f")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("1ff035a6-5d40-4a2d-aa9c-1d3182b3642e")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("ec733d3f-cf8b-475c-8af6-5881cdb65dbe")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("ac804e8f-abe7-4516-927f-045477dbe007")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("5be9a36e-c59c-4a9a-a800-15f4f76ea80b")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("fbeb18d0-5e5f-4a38-aec7-6bb314408dc7")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("b2fe4d1c-59b9-4161-8eab-04380b45fd5e")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("bb5cb9b7-75d0-4a9f-81d9-d02259b6ddf2")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("30bb7d98-1a11-4152-9481-9a9d5fd39041")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("5bc63b8d-2825-4f0e-aeae-234c7b2d930f")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("afe7776a-69a6-4134-96ea-a24829c67c9d")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("8694cd0d-8987-44b4-b823-3f2e7f023919")
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            UserId = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            UserId = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7")
                        });
                });

            modelBuilder.Entity("AppTemplate.Domain.AppUsers.AppUser", b =>
                {
                    b.HasOne("AppTemplate.Domain.AppUsers.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppTemplate.Domain.AppUsers.AppUser", "DeletedBy")
                        .WithMany("DeletedUsers")
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("AppTemplate.Domain.AppUsers.AppUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTemplate.Domain.AppUsers.AppUser", "UpdatedBy")
                        .WithMany("UpdatedUsers")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("AppTemplate.Domain.AppUsers.ValueObjects.NotificationPreference", "NotificationPreference", b1 =>
                        {
                            b1.Property<Guid>("AppUserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsEmailNotificationEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("email_notification");

                            b1.Property<bool>("IsInAppNotificationEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("in_app_notification");

                            b1.Property<bool>("IsPushNotificationEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("push_notification");

                            b1.HasKey("AppUserId");

                            b1.ToTable("AppUsers");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");

                            b1.HasData(
                                new
                                {
                                    AppUserId = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7"),
                                    IsEmailNotificationEnabled = true,
                                    IsInAppNotificationEnabled = true,
                                    IsPushNotificationEnabled = true
                                });
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("IdentityUser");

                    b.Navigation("NotificationPreference")
                        .IsRequired();

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AppTemplate.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("AppTemplate.Domain.AppUsers.AppUser", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("AppTemplate.Domain.Roles.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permissions_PermissionId");

                    b.HasOne("AppTemplate.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Roles_RoleId");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("AppTemplate.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleUser_Roles_RoleId");

                    b.HasOne("AppTemplate.Domain.AppUsers.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleUser_AppUsers_UserId");
                });

            modelBuilder.Entity("AppTemplate.Domain.AppUsers.AppUser", b =>
                {
                    b.Navigation("DeletedUsers");

                    b.Navigation("Notifications");

                    b.Navigation("UpdatedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
