// <auto-generated />
using System;
using AppTemplate.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppTemplate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250326215516_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppTemplate.Domain.AppUsers.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 423, DateTimeKind.Utc).AddTicks(3910),
                            IdentityId = "b3398ff2-1b43-4af7-812d-eb4347eecbb8"
                        });
                });

            modelBuilder.Entity("AppTemplate.Domain.Roles.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33261a4a-c423-4876-8f15-e40068aea5ca"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(7605),
                            Feature = "users",
                            Name = "users:read"
                        },
                        new
                        {
                            Id = new Guid("9f79a54c-0b54-4de5-94b9-8582a5f32e78"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9069),
                            Feature = "users",
                            Name = "users:create"
                        },
                        new
                        {
                            Id = new Guid("25bb194c-ea15-4339-9f45-5a895c51b626"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9074),
                            Feature = "users",
                            Name = "users:update"
                        },
                        new
                        {
                            Id = new Guid("559dd4ec-4d2e-479d-a0a9-5229ecc04fb4"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9075),
                            Feature = "users",
                            Name = "users:delete"
                        },
                        new
                        {
                            Id = new Guid("d066e4ee-6af2-4857-bd40-b9b058fa2201"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9077),
                            Feature = "roles",
                            Name = "roles:read"
                        },
                        new
                        {
                            Id = new Guid("940c88ad-24fe-4d86-a982-fa5ea224edba"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9078),
                            Feature = "roles",
                            Name = "roles:create"
                        },
                        new
                        {
                            Id = new Guid("346d3cc6-ac81-42b1-8539-cd53f42b6566"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9080),
                            Feature = "roles",
                            Name = "roles:update"
                        },
                        new
                        {
                            Id = new Guid("386e40e9-da38-4d2f-8d02-ac4cbaddf760"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9081),
                            Feature = "roles",
                            Name = "roles:delete"
                        },
                        new
                        {
                            Id = new Guid("0eeb5f27-10fd-430a-9257-a8457107141a"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9083),
                            Feature = "permissions",
                            Name = "permissions:read"
                        },
                        new
                        {
                            Id = new Guid("3050d953-5dcf-4eb0-a18d-a3ce62a0dd3c"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9084),
                            Feature = "auditlogs",
                            Name = "auditlogs:read"
                        },
                        new
                        {
                            Id = new Guid("a03a127b-9a03-46a0-b709-b6919f2598be"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9086),
                            Feature = "notifications",
                            Name = "notifications:read"
                        },
                        new
                        {
                            Id = new Guid("a5585e9e-ec65-431b-9bb9-9bbc1663ebb8"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 426, DateTimeKind.Utc).AddTicks(9087),
                            Feature = "notifications",
                            Name = "notifications:update"
                        });
                });

            modelBuilder.Entity("AppTemplate.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 432, DateTimeKind.Utc).AddTicks(2657),
                            IsDefault = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            CreatedBy = "System",
                            CreatedOnUtc = new DateTime(2025, 3, 26, 21, 55, 15, 432, DateTimeKind.Utc).AddTicks(3113),
                            IsDefault = true,
                            Name = "Registered"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b3398ff2-1b43-4af7-812d-eb4347eecbb8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6b1015e-397e-4251-8559-aef7fc8a6a58",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHIU5u89fB0DtgDjmowFzlj1AyWVMP1Q6bz+zueZKex/vzQIIRFTQzSOsLy2veEhjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e24ddd3-fd6e-4cee-831d-82573724aa1f",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Myrtus.Clarity.Core.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("33261a4a-c423-4876-8f15-e40068aea5ca")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("9f79a54c-0b54-4de5-94b9-8582a5f32e78")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("25bb194c-ea15-4339-9f45-5a895c51b626")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("559dd4ec-4d2e-479d-a0a9-5229ecc04fb4")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("d066e4ee-6af2-4857-bd40-b9b058fa2201")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("940c88ad-24fe-4d86-a982-fa5ea224edba")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("346d3cc6-ac81-42b1-8539-cd53f42b6566")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("386e40e9-da38-4d2f-8d02-ac4cbaddf760")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("0eeb5f27-10fd-430a-9257-a8457107141a")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("3050d953-5dcf-4eb0-a18d-a3ce62a0dd3c")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("a03a127b-9a03-46a0-b709-b6919f2598be")
                        },
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            PermissionId = new Guid("a5585e9e-ec65-431b-9bb9-9bbc1663ebb8")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("a03a127b-9a03-46a0-b709-b6919f2598be")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("a5585e9e-ec65-431b-9bb9-9bbc1663ebb8")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            PermissionId = new Guid("33261a4a-c423-4876-8f15-e40068aea5ca")
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("4b606d86-3537-475a-aa20-26aadd8f5cfd"),
                            UserId = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7")
                        },
                        new
                        {
                            RoleId = new Guid("5dc6ec47-5b7c-4c2b-86cd-3a671834e56e"),
                            UserId = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7")
                        });
                });

            modelBuilder.Entity("AppTemplate.Domain.AppUsers.AppUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("AppTemplate.Domain.AppUsers.AppUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AppTemplate.Domain.AppUsers.ValueObjects.NotificationPreference", "NotificationPreference", b1 =>
                        {
                            b1.Property<Guid>("AppUserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsEmailNotificationEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("email_notification");

                            b1.Property<bool>("IsInAppNotificationEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("in_app_notification");

                            b1.Property<bool>("IsPushNotificationEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("push_notification");

                            b1.HasKey("AppUserId");

                            b1.ToTable("AppUsers");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");

                            b1.HasData(
                                new
                                {
                                    AppUserId = new Guid("55c7f429-0916-4d84-8b76-d45185d89aa7"),
                                    IsEmailNotificationEnabled = true,
                                    IsInAppNotificationEnabled = true,
                                    IsPushNotificationEnabled = true
                                });
                        });

                    b.Navigation("IdentityUser");

                    b.Navigation("NotificationPreference")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("AppTemplate.Domain.Roles.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permissions_PermissionId");

                    b.HasOne("AppTemplate.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Roles_RoleId");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("AppTemplate.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleUser_Roles_RoleId");

                    b.HasOne("AppTemplate.Domain.AppUsers.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleUser_AppUsers_UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
